/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 scene.gltf --transform
Author: coconut_crab (https://sketchfab.com/coconut_crab)
License: CC-BY-SA-4.0 (http://creativecommons.org/licenses/by-sa/4.0/)
Source: https://sketchfab.com/3d-models/hamster-eaace4e2c59843198f0443243a1f26f4
Title: hamster
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Hamster(props) {
  const { nodes, materials } = useGLTF(
    "../animations/rodents/hamster/scene-transformed.glb"
  );
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Object_2.geometry}
        material={materials.material}
        rotation={[-Math.PI / 2, -0.1, 5]}
      />
    </group>
  );
}

useGLTF.preload("../animations/rodents/hamster/scene-transformed.glb");
