/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 scene.gltf --transform
Author: marcomazzo (https://sketchfab.com/marcomazzo)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/squirrel-e602573e900f432eb5d431648d5de76b
Title: Squirrel
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Squirrel(props) {
  const { nodes, materials } = useGLTF(
    "../animations/rodents/squirrel/scene-transformed.glb"
  );
  return (
    <group {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, Math.PI]}>
        <group rotation={[-Math.PI, 0, 1.5]}>
          <mesh
            geometry={nodes.VioletSquirrel_v0_hipoly_simplified__0.geometry}
            material={materials["Scene_-_Root"]}
          />
          <mesh
            geometry={nodes.VioletSquirrel_v0_hipoly_simplified__0_1.geometry}
            material={materials["Scene_-_Root"]}
          />
          <mesh
            geometry={nodes.VioletSquirrel_v0_hipoly_simplified__0_2.geometry}
            material={materials["Scene_-_Root"]}
          />
          <mesh
            geometry={nodes.VioletSquirrel_v0_hipoly_simplified__0_3.geometry}
            material={materials["Scene_-_Root"]}
          />
          <mesh
            geometry={nodes.VioletSquirrel_v0_hipoly_simplified__0_4.geometry}
            material={materials["Scene_-_Root"]}
          />
          <mesh
            geometry={nodes.VioletSquirrel_v0_hipoly_simplified__0_5.geometry}
            material={materials["Scene_-_Root"]}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("../animations/rodents/squirrel/scene-transformed.glb");
