/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 scene.gltf --transform
Author: sidarthmenon (https://sketchfab.com/sidarthmenon)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/rover-c06453eb88544733b1d7f5b9ded70a19
Title: Rover
*/

import React, { useRef, useEffect } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export function Animation(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF(
    "../animations/dog/scene-transformed.glb"
  );
  const { actions } = useAnimations(animations, group);

  useEffect(() => {
    actions.ClickedOn.play();
    actions._CharacterSucceeds.play();
  }, []);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group name="GLTF_created_0">
                <primitive object={nodes.GLTF_created_0_rootJoint} />
                <skinnedMesh
                  name="Object_68"
                  geometry={nodes.Object_68.geometry}
                  material={materials.material_0}
                  skeleton={nodes.Object_68.skeleton}
                />
                <skinnedMesh
                  name="Object_71"
                  geometry={nodes.Object_71.geometry}
                  material={materials.material_1}
                  skeleton={nodes.Object_71.skeleton}
                />
                <skinnedMesh
                  name="Object_74"
                  geometry={nodes.Object_74.geometry}
                  material={materials.material_1}
                  skeleton={nodes.Object_74.skeleton}
                />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("../animations/dog/scene-transformed.glb");
