/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 scene.gltf --transform
Author: BlueMesh (https://sketchfab.com/VapTor)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/betta-splendens-f4eeb7f50ad24873842bd954ad27d23b
Title: Betta Splendens
*/
import { useFrame } from "@react-three/fiber";
import React, { useRef, useEffect } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export function Betta1(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF(
    "../animations/fish/betta1/scene-transformed.glb"
  );
  const { actions } = useAnimations(animations, group);

  useEffect(() => {
    actions.Take.play();
  }, []);

  const speed = 0.3;
  useFrame(({ clock }) => {
    const time = clock.elapsedTime * speed;
    const x = -Math.sin(time) * 8; // replace with desired movement equation
    const y = -1.5;
    const z = 3; // replace with desired movement equation
    group.current.position.set(x, y, z);
    group.current.rotation.y = time; // replace with desired rotation equation
  });

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2.5, 0, 0]}>
          <group name="Root">
            <group name="Cube" position={[0, -2.84, 3.6]} scale={0.26}>
              <group name="Armature" position={[0, 1.68, -8.5]} scale={3.88}>
                <group
                  name="EYES"
                  position={[0.15, -0.08, 0.05]}
                  scale={[0.09, 0.12, 0.12]}
                />
                <primitive object={nodes.Armature_rootJoint} />
                <skinnedMesh
                  name="BODY_0"
                  geometry={nodes.BODY_0.geometry}
                  material={materials.BETTA}
                  skeleton={nodes.BODY_0.skeleton}
                />
                <skinnedMesh
                  name="EYES_0"
                  geometry={nodes.EYES_0.geometry}
                  material={materials.BETTA}
                  skeleton={nodes.EYES_0.skeleton}
                />
              </group>
              <mesh
                name="Cube_0"
                geometry={nodes.Cube_0.geometry}
                material={materials.Root}
              />
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("../animations/fish/betta1/scene-transformed.glb");
