/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 scene.gltf --transform
Author: dhar (https://sketchfab.com/Dharia.Pitman)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/low-poly-killifish-aecd87ffb2cb4e7db94962727c58237c
Title: Low Poly Killifish
*/

import { useFrame } from "@react-three/fiber";
import React, { useRef, useEffect } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export function Killifish(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF(
    "../animations/fish/killifish/scene-transformed.glb"
  );
  const { actions } = useAnimations(animations, group);

  useEffect(() => {
    actions.Swim.play();
  });

  const speed = 0.35;
  useFrame(({ clock }) => {
    const time = clock.elapsedTime * speed;
    const x = -Math.sin(time) * 8; // replace with desired movement equation
    const y = -5;
    const z = Math.cos(time) * 9; // replace with desired movement equation
    group.current.position.set(x, y, z);
    group.current.rotation.y = time; // replace with desired rotation equation
  });

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group name="Rig_9" rotation={[Math.PI / 2, 0, Math.PI]}>
                <group name="GLTF_created_0">
                  <primitive object={nodes.GLTF_created_0_rootJoint} />
                  <skinnedMesh
                    name="Object_7"
                    geometry={nodes.Object_7.geometry}
                    material={materials.Killifsh_Texture}
                    skeleton={nodes.Object_7.skeleton}
                  />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("../animations/fish/killifish/scene-transformed.glb");
