/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 scene.gltf --transform
Author: yannoch (https://sketchfab.com/yannoch)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/game-asset-planktomania-krill-f8a4d1ba05bc46ccaf32ed6cd7e40ce9
Title: Game asset - Planktomania - Krill
*/

import { useFrame } from "@react-three/fiber";
import React, { useRef, useEffect } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export function Plankton(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF(
    "../animations/fish/plankton/scene-transformed.glb"
  );
  const { actions } = useAnimations(animations, group);

  useEffect(() => {
    actions.Swim.play();
  });

  const speed = 0.35;
  useFrame(({ clock }) => {
    const time = clock.elapsedTime * speed;
    const x = -Math.sin(time) * 8; // replace with desired movement equation
    const y = -3;
    const z = Math.cos(time) * 8; // replace with desired movement equation
    group.current.position.set(x, y, z);
    group.current.rotation.y = time; // replace with desired rotation equation
  });

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group
            name="8caccb49b10a47d2ab97b19d7cff79f7fbx"
            rotation={[Math.PI / 2, 0, 0]}
          >
            <group name="Object_2">
              <group name="RootNode">
                <group name="Neutre_5" position={[0, -0.95, 12.07]} />
                <group name="Racine" position={[0, 1.61, 0.11]}>
                  <group name="Object_16">
                    <primitive object={nodes._rootJoint} />
                    <skinnedMesh
                      name="Object_186"
                      geometry={nodes.Object_186.geometry}
                      material={materials.Default}
                      skeleton={nodes.Object_186.skeleton}
                    />
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("../animations/fish/plankton/scene-transformed.glb");
