/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 scene.gltf --transform
Author: Macauley.B (https://sketchfab.com/Macauley.B)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/rockatoo-character-1595e8668689427f87cffb2b0daf99e5
Title: Rockatoo character
*/

import React, { useRef, useEffect } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export function Bird3(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF(
    "../animations/birds/bird3/scene-transformed.glb"
  );
  const { actions } = useAnimations(animations, group);

  useEffect(() => {
    actions.Animation_01.play();
    // console.log(actions)
  });
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group
            name="8374cf854de947bda626dc512df6934cfbx"
            rotation={[Math.PI / 2, 0, 0]}
          >
            <group name="Object_2">
              <group name="RootNode">
                <group
                  name="cockatoo_Main_ctrl"
                  position={[0, 18.87, -24.32]}
                  rotation={[0, -1.57, 0]}
                >
                  <group name="Object_5">
                    <primitive object={nodes._rootJoint} />
                    <skinnedMesh
                      name="Object_168"
                      geometry={nodes.Object_168.geometry}
                      material={materials.Cockatoo_D}
                      skeleton={nodes.Object_168.skeleton}
                    />
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("../animations/birds/bird3/scene-transformed.glb");
