/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 scene.gltf --transform
Author: tojamerlin (https://sketchfab.com/tojamerlin)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/lilyturf-817b0b067f8942c1b8976c338d59982e
Title: Lilyturf
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Lavender(props) {
  const { nodes, materials } = useGLTF('../animations/plants/lavender/scene-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.lilyturf_Stem_0.geometry} material={materials.Stem} />
      <mesh geometry={nodes.lilyturf_Leaf_0.geometry} material={materials.Leaf} />
      <mesh geometry={nodes.lilyturf_Leaf_0_1.geometry} material={materials.Leaf} />
      <mesh geometry={nodes.lilyturf_Leaf_0_2.geometry} material={materials.Leaf} />
      <mesh geometry={nodes.lilyturf_Leaf_0_3.geometry} material={materials.Leaf} />
      <mesh geometry={nodes.lilyturf_Leaf_0_4.geometry} material={materials.Leaf} />
      <mesh geometry={nodes.lilyturf_Leaf_0_5.geometry} material={materials.Leaf} />
      <mesh geometry={nodes.lilyturf_Leaf_0_6.geometry} material={materials.Leaf} />
      <mesh geometry={nodes.lilyturf_Leaf_0_7.geometry} material={materials.Leaf} />
      <mesh geometry={nodes.grass_Grass_0.geometry} material={materials.Grass} />
    </group>
  )
}

useGLTF.preload('../animations/plants/lavender/scene-transformed.glb')
