/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 scene.gltf --transform
Author: MyVisoin (https://sketchfab.com/TemurG)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/purple-lilies-a73ee85609bf48ef98eb08b29590e40f
Title: Purple lilies
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Liliac(props) {
  const { nodes, materials } = useGLTF('../animations/plants/liliac/scene-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_4.geometry} material={materials.Material} />
      <mesh geometry={nodes.Object_5.geometry} material={materials.Material} />
      <mesh geometry={nodes.Object_6.geometry} material={materials.Material} />
      <mesh geometry={nodes.Object_7.geometry} material={materials.Material} />
      <mesh geometry={nodes.Object_8.geometry} material={materials.Material} />
      <mesh geometry={nodes.Object_9.geometry} material={materials.Material} />
      <mesh geometry={nodes.Object_10.geometry} material={materials.Material} />
    </group>
  )
}

useGLTF.preload('../animations/plants/liliac/scene-transformed.glb')
