/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 scene.gltf --transform
Author: dipietron (https://sketchfab.com/dipietron)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/madrona-invasives-6e1e4cf5c6d74da286cbf425a939c9ce
Title: Madrona Invasives
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Tree(props) {
  const { nodes, materials } = useGLTF(
    "../animations/plants/tree/scene-transformed.glb"
  );
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.53}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <mesh
            geometry={nodes.Tilt_Brush7722_0.geometry}
            material={materials.Wire_4278271387}
          />
          <mesh
            geometry={nodes.Tilt_Brush7722_0_1.geometry}
            material={materials.Wire_4278271387}
          />
          <mesh
            geometry={nodes.Tilt_Brush7722_0_2.geometry}
            material={materials.Wire_4278271387}
          />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <mesh
            geometry={nodes.Tilt_Brush10137_0.geometry}
            material={materials.OilPaint_4282157053}
          />
          <mesh
            geometry={nodes.Tilt_Brush10137_0_1.geometry}
            material={materials.OilPaint_4282157053}
          />
          <mesh
            geometry={nodes.Tilt_Brush10137_0_2.geometry}
            material={materials.OilPaint_4282157053}
          />
        </group>
        <mesh
          geometry={nodes.Tilt_Brush7143_0.geometry}
          material={materials.Wire_4279146624}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
        <mesh
          geometry={nodes.Tilt_Brush7219_0.geometry}
          material={materials.Ink_4279146624}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
        <mesh
          geometry={nodes.Tilt_Brush7440_0.geometry}
          material={materials.ThickPaint_819821}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
        <mesh
          geometry={nodes.Tilt_Brush8145_0.geometry}
          material={materials.Wire_4278349609}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
        <mesh
          geometry={nodes.Tilt_Brush8541_0.geometry}
          material={materials.Ink_4287233202}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
        <mesh
          geometry={nodes.Tilt_Brush8769_0.geometry}
          material={materials.Wire_4282157053}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
        <mesh
          geometry={nodes.Tilt_Brush14082_0.geometry}
          material={materials.Ink_4282157053}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
        <mesh
          geometry={nodes.Tilt_Brush14553_0.geometry}
          material={materials.OilPaint_4278429502}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
        <mesh
          geometry={nodes.Tilt_Brush16371_0.geometry}
          material={materials.OilPaint_4278806872}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
        <mesh
          geometry={nodes.Tilt_Brush17437_0.geometry}
          material={materials.Ink_4291813886}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
        <mesh
          geometry={nodes.Tilt_Brush17557_0.geometry}
          material={materials.Wire_4293000439}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
        <mesh
          geometry={nodes.Tilt_Brush17639_0.geometry}
          material={materials.Wire_4287806718}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
        <mesh
          geometry={nodes.Tilt_Brush17874_0.geometry}
          material={materials.OilPaint_4287806718}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
        <mesh
          geometry={nodes.Tilt_Brush18373_0.geometry}
          material={materials.Ink_4287806718}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
      </group>
    </group>
  );
}

useGLTF.preload("../animations/plants/tree/scene-transformed.glb");
